# Korbit AI Configuration
# Enable automatic code reviews for this repository

# Enable Korbit for this repository
enabled: true

# File patterns to analyze
include:
  - "src/**/*.py"
  - "tests/**/*.py"
  - "scripts/**/*.py"
  - "*.py"

# File patterns to exclude from analysis
exclude:
  - "__pycache__/**"
  - "*.pyc"
  - ".git/**"
  - "node_modules/**"
  - ".coverage"
  - "*.log"
  - "venv/**"
  - ".venv/**"

# Language-specific settings
languages:
  python:
    enabled: true

# Review settings
reviews:
  # Enable automatic PR reviews
  pull_requests: true
  # Enable commit analysis
  commits: true
  # Focus areas for this AI/ML repository
  focus:
    - security
    - performance
    - maintainability
    - bugs
